### ISSUE TITLE
When I select this singer in OpenUtau, no matter if I edit words or edit phonemes, when I play, I always get this error. I followed the instructions in the error and installed the latest versions of nsf_hifigan.oudep and nsf_hifigan_44.1k_hop512_128bin_2024.02.oudep, but I still encounter errors. Do you know what the problem is?

### ISSUE THREAD

**Issue by Oliver0621** [julieraptor/DIFFSINGER-LIEE-Immortal-Idol#1]
Failed to render.
Error loading vocoder fish_hifigan. Please download vocoder from https://github.com/xunmengshe/OpenUtau/wiki/Vocoders

System.AggregateException: One or more errors occurred. (Error loading vocoder fish_hifigan. Please download vocoder from https://github.com/xunmengshe/OpenUtau/wiki/Vocoders)
 ---> System.Exception: Error loading vocoder fish_hifigan. Please download vocoder from https://github.com/xunmengshe/OpenUtau/wiki/Vocoders
   at OpenUtau.Core.DiffSinger.DsVocoder..ctor(String name) in D:\a\OpenUtau\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerVocoder.cs:line 32
   at OpenUtau.Core.DiffSinger.DiffSingerSinger.getVocoder() in D:\a\OpenUtau\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerSinger.cs:line 153
   at OpenUtau.Core.DiffSinger.DiffSingerRenderer.InvokeDiffsinger(RenderPhrase phrase, Int32 depth, Int32 speedup, CancellationTokenSource cancellation) in D:\a\OpenUtau\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerRenderer.cs:line 394
   at OpenUtau.Core.DiffSinger.DiffSingerRenderer.<>c__DisplayClass15_0.<Render>b__0() in D:\a\OpenUtau\OpenUtau\OpenUtau.Core\DiffSinger\DiffSingerRenderer.cs:line 119
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

0.1.429.39
<img width="1126" alt="Ov7p2xtz0q" src="https://github.com/julieraptor/DIFFSINGER-LIEE-Immortal-Idol/assets/137243056/02276ff7-131e-4af7-906f-1af4d7496cbe">
<img width="1022" alt="UczxywO5pG" src="https://github.com/julieraptor/DIFFSINGER-LIEE-Immortal-Idol/assets/137243056/3eec4ffd-58b3-4548-b96c-eea8f74ac726">

**Comment by Oliver0621** [comment]
I know the reason. It seems that the Vocoders name in the singer configuration file is written incorrectly. The correct name should be : nsf_hifigan

<img width="523" alt="lzXWKQq2iZ" src="https://github.com/julieraptor/DIFFSINGER-LIEE-Immortal-Idol/assets/137243056/c58d072d-e437-4b39-ab28-269e990bdd8a">

![image](https://github.com/julieraptor/DIFFSINGER-LIEE-Immortal-Idol/assets/137243056/79f6d7b1-96dc-4d31-b38c-696eab0f1e41)

**Comment by julieraptor** [comment]
Yes, please find the vocoder fish_hifigan, or change vocoder in dsconfig.yaml to nsf_hifigan. Apologies for this issue!
